<?php

/**
 * BaseTicketTracking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $operator_id
 * @property integer $actor_id
 * @property Doctrine_Collection $TicketTrackingEntry
 * 
 * @method integer             getOperatorId()          Returns the current record's "operator_id" value
 * @method integer             getActorId()             Returns the current record's "actor_id" value
 * @method Doctrine_Collection getTicketTrackingEntry() Returns the current record's "TicketTrackingEntry" collection
 * @method TicketTracking      setOperatorId()          Sets the current record's "operator_id" value
 * @method TicketTracking      setActorId()             Sets the current record's "actor_id" value
 * @method TicketTracking      setTicketTrackingEntry() Sets the current record's "TicketTrackingEntry" collection
 * 
 * @package    tracking.sol-violette.info
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTicketTracking extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ticket_tracking');
        $this->hasColumn('operator_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('actor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TicketTrackingEntry', array(
             'local' => 'id',
             'foreign' => 'ticket_tracking_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}