<?php

/**
 * BaseTicketTrackingEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $status
 * @property integer $ticket_id
 * @property integer $ticket_tracking_id
 * @property TicketTracking $TicketTracking
 * @property Ticket $Ticket
 * 
 * @method integer             getStatus()             Returns the current record's "status" value
 * @method integer             getTicketId()           Returns the current record's "ticket_id" value
 * @method integer             getTicketTrackingId()   Returns the current record's "ticket_tracking_id" value
 * @method TicketTracking      getTicketTracking()     Returns the current record's "TicketTracking" value
 * @method Ticket              getTicket()             Returns the current record's "Ticket" value
 * @method TicketTrackingEntry setStatus()             Sets the current record's "status" value
 * @method TicketTrackingEntry setTicketId()           Sets the current record's "ticket_id" value
 * @method TicketTrackingEntry setTicketTrackingId()   Sets the current record's "ticket_tracking_id" value
 * @method TicketTrackingEntry setTicketTracking()     Sets the current record's "TicketTracking" value
 * @method TicketTrackingEntry setTicket()             Sets the current record's "Ticket" value
 * 
 * @package    tracking.sol-violette.info
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTicketTrackingEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ticket_tracking_entry');
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ticket_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ticket_tracking_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('created_at_index', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TicketTracking', array(
             'local' => 'ticket_tracking_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Ticket', array(
             'local' => 'ticket_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}