<?php

/**
 * TicketTrackingEntry
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    tracking.sol-violette.info
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TicketTrackingEntry extends BaseTicketTrackingEntry
{

	const STATUS_UPDATED = 1;
	const STATUS_CONFIRMED = 2;
	const STATUS_NEW = 3;
	const STATUS_EXPIRED = 4;


}