<?php

/**
 * TicketTrackingTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketTrackingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketTrackingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketTracking');
    }
}