<?php

/**
 * Ticket
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package tracking.sol-violette.info
 * @subpackage model
 * @author Your name here
 * @version SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ticket extends BaseTicket {
    const STATUS_ENABLED = 1;
    const STATUS_DISABLED = 2;

    public function getLastOwner()
    {
        $result = Doctrine_Query::create()->from('TicketTrackingEntry e')->leftJoin('e.TicketTracking tt')
        	->where("e.ticket_id = ?", $this->id)->addOrderBy('e.created_at DESC')
        	->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);

        if ($result) {
//        	echo '<pre>';
//        	print_r($result); exit;
        	if($result['TicketTracking']['is_remove_action']){
        		return false;
        	}
            return $result['TicketTracking']['actor_id'];
        }

        return false;
    }
}